services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Lemming\ImgProxy\:
    resource: '../Classes/*'

  Lemming\ImgProxy\EventListener\BeforeFileProcessing:
    tags:
      - name: event.listener
        identifier: 'imgproxy'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent